BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "entrants" (
	"EventCode"	TEXT NOT NULL,
	"EntrantNumber"	INTEGER NOT NULL DEFAULT 0,
	"RecordStatus"	INTEGER NOT NULL DEFAULT 0,
	"DateCreated"	TEXT NOT NULL,
	"DateUpdated"	TEXT,
	"RiderFirst"	TEXT NOT NULL,
	"RiderLast"	TEXT NOT NULL,
	"RiderIBA"	TEXT,
	"RiderRBL"	TEXT DEFAULT 'N',
	"RiderAddr1"	TEXT,
	"RiderAddr2"	TEXT,
	"RiderTown"	TEXT,
	"RiderCounty"	TEXT,
	"RiderPostcode"	TEXT,
	"RiderCountry"	TEXT,
	"RiderPhone"	TEXT,
	"RiderEmail"	TEXT,
	"RiderNoviceYN"	TEXT NOT NULL DEFAULT 'N',
	"HasPillionYN"	TEXT NOT NULL DEFAULT 'N',
	"PillionFirst"	TEXT,
	"PillionLast"	TEXT,
	"PillionIBA"	TEXT,
	"PillionRBL"	TEXT DEFAULT 'N',
	"PillionAddr1"	TEXT,
	"PillionAddr2"	TEXT,
	"PillionTown"	TEXT,
	"PillionCounty"	TEXT,
	"PillionPostcode"	TEXT,
	"PillionCountry"	TEXT,
	"PillionPhone"	TEXT,
	"PillionEmail"	TEXT,
	"PillionNoviceYN"	TEXT NOT NULL DEFAULT 'N',
	"Bike"	TEXT NOT NULL DEFAULT 'motorbike',
	"BikeReg"	TEXT,
	"OdoCountsMK"	TEXT NOT NULL DEFAULT 'M',
	"NokName"	TEXT,
	"NokPhone"	TEXT,
	"NokRelation"	TEXT,
	"Tshirts"	TEXT,
	"Patches"	INTEGER NOT NULL DEFAULT 0,
	"RouteClass"	TEXT NOT NULL DEFAULT '',
	"FreeCampingYN"	TEXT NOT NULL DEFAULT 'N',
	"Sponsorship"	TEXT,
	"PaymentMethod"	TEXT NOT NULL DEFAULT 'PAYPAL'
);
CREATE TABLE IF NOT EXISTS "events" (
	"EventCode"	TEXT NOT NULL,
	"EventTitle"	TEXT NOT NULL,
	"NoviceEvent" TEXT NOT NULL DEFAULT 'rally',
	"RiderFee"	TEXT NOT NULL,
	"PillionFee"	TEXT NOT NULL,
	"TshirtFee"	TEXT NOT NULL,
	"PatchFee"	TEXT NOT NULL,
	"MaxTshirts"	INTEGER NOT NULL DEFAULT 2,
	"MaxPatches"	INTEGER NOT NULL DEFAULT 2,
	"RouteClasses"	TEXT NOT NULL DEFAULT '',
	"OfferCampingYN"	TEXT NOT NULL DEFAULT 'N',
	"PaymentMethods"	TEXT NOT NULL DEFAULT 'PAYPAL',
	"SponsorshipOptions"	TEXT NOT NULL DEFAULT ''
);
COMMIT;
